# Generated by Django 5.2.6 on 2025-09-13 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Temperature', 'Temperature'), ('Pressure', 'Pressure'), ('Humidity', 'Humidity'), ('Vibration', 'Vibration'), ('Flow', 'Flow')], max_length=20)),
                ('value', models.FloatField(default=0.0)),
                ('unit', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('warning', 'Warning'), ('critical', 'Critical'), ('offline', 'Offline')], default='online', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('drift', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF')], max_length=20)),
                ('file_path', models.CharField(max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('linear', 'Linear'), ('polynomial', 'Polynomial'), ('custom', 'Custom')], max_length=50)),
                ('params', models.JSONField(default=dict)),
                ('corrected_value', models.FloatField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Drift', 'Drift'), ('Spike', 'Spike'), ('Dropout', 'Dropout'), ('Noise', 'Noise'), ('Calibration Error', 'Calibration Error')], max_length=50)),
                ('value', models.FloatField()),
                ('expected', models.FloatField()),
                ('deviation', models.FloatField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='sensors.sensor')),
            ],
        ),
    ]
